seleniumhub:
  image: selenium/hub
  ports:
    - 4444:4444

seleniumfox:
  image: selenium/node-firefox
  ports:
    - 5900
  links:
    - seleniumhub:hub

seleniumphantomjs:
  image: akeem/selenium-node-phantomjs
  ports:
    - 5900
  links:
    - seleniumhub:hub
